import { AuthProvider } from './context/AuthContext';
import 'semantic-ui-css/semantic.min.css'
import { Inter } from 'next/font/google'
import "./scss/global.scss";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

// @/app/scss/global.scss

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gamming',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div>{children}</div>
        </AuthProvider>
      </body>
    </html>
  )
}